'use client'

import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  ResponsiveContainer, 
  LineChart, 
  Line 
} from 'recharts'
import { Download, FileText } from 'lucide-react'
import { exportToCSV, exportToPDF } from '@/lib/export'
import { useState } from 'react'

interface AnalyticsChartsProps {
  expenseTrendData: any[]
  roiData: any[]
  exportData: any[]
}

export default function AnalyticsCharts({ expenseTrendData, roiData, exportData }: AnalyticsChartsProps) {
  const [isExportingPDF, setIsExportingPDF] = useState(false)

  const handleExportCSV = () => {
    exportToCSV(exportData, 'fuel-expenses-report')
  }

  const handleExportPDF = async () => {
    setIsExportingPDF(true)
    await exportToPDF('analytics-report-area', 'FleetFlow-Analytics')
    setIsExportingPDF(false)
  }

  return (
    <div className="space-y-6" id="analytics-report-area">
      <div className="flex justify-end gap-3 mb-4 no-print print:hidden">
        <Button variant="outline" size="sm" onClick={handleExportCSV}>
          <FileText className="w-4 h-4 mr-2 text-emerald-600" />
          Export Data (CSV)
        </Button>
        <Button variant="outline" size="sm" onClick={handleExportPDF} disabled={isExportingPDF}>
          <Download className="w-4 h-4 mr-2 text-red-600" />
          {isExportingPDF ? 'Generating...' : 'Download Report (PDF)'}
        </Button>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <Card className="shadow-sm">
          <CardHeader>
            <CardTitle className="text-lg">Monthly Expenses Trend</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-80 w-full">
              {expenseTrendData.length === 0 ? (
                <div className="flex h-full items-center justify-center text-neutral-400">Not enough data to graph</div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={expenseTrendData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                    <XAxis dataKey="month" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis stroke="#888888" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`} />
                    <Tooltip contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                    <Legend />
                    <Line type="monotone" dataKey="fuel" name="Fuel ($)" stroke="#6324eb" strokeWidth={2} dot={{ r: 4 }} activeDot={{ r: 6 }} />
                    <Line type="monotone" dataKey="maintenance" name="Maintenance ($)" stroke="#ef4444" strokeWidth={2} dot={{ r: 4 }} />
                  </LineChart>
                </ResponsiveContainer>
              )}
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-sm">
          <CardHeader>
            <CardTitle className="text-lg">Vehicle Profitability (ROI)</CardTitle>
            <p className="text-xs text-neutral-500 m-0">Revenue vs Configured Costs (Fuel + Maint)</p>
          </CardHeader>
          <CardContent>
            <div className="h-80 w-full">
              {roiData.length === 0 ? (
                <div className="flex h-full items-center justify-center text-neutral-400">Not enough data to graph</div>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={roiData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }} layout="vertical">
                    <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" horizontal={true} vertical={false} />
                    <XAxis type="number" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value}`} />
                    <YAxis dataKey="name" type="category" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} width={100} />
                    <Tooltip contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                    <Legend />
                    <Bar dataKey="revenue" name="Total Revenue" fill="#10b981" radius={[0, 4, 4, 0]} barSize={12} />
                    <Bar dataKey="costs" name="Total Costs" fill="#f43f5e" radius={[0, 4, 4, 0]} barSize={12} />
                  </BarChart>
                </ResponsiveContainer>
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="mt-8 text-center text-xs text-neutral-400">
        Generated by FleetFlow Engine • {new Date().toLocaleDateString()}
      </div>
    </div>
  )
}
